### ISSUE TITLE
Allow for theme-specific styling of in-text citations

### ISSUE THREAD

**Issue by nokome** [stencila/thema#283]
I have made some recent changes in Encoda that improve the handling of in-text citations. This includes handling numeric style citations e.g. `[7,8]`. If the `content` property of a `Cite` node is undefined, then the HTML codec will encode two spans, one with class `cite-numeric` and one with `cite-authors-years`. e.g.

```html
<span itemscope="" itemtype="http://schema.stenci.la/CiteGroup"><cite itemscope="" itemtype="http://schema.stenci.la/Cite"><a href="#ref7"><span class="cite-numeric">7</span><span class="cite-authors-year">Schubert et al.,
                  2013</span></a></cite><cite itemscope="" itemtype="http://schema.stenci.la/Cite"><a href="#ref8"><span class="cite-numeric">8</span><span class="cite-authors-year">Soria-Guerra et al.,
                  2015</span></a></cite></span>
```

The intention is to hide one or the other. ie. a theme using numeric citations would put square brackets `:before` and `:after` the `CiteGroup` and hide the `span.cite-authors-year`.

This introduces classes to the HTML, which have generally avoided. But in this case it seems warranted because it's purely presentational? @alex-ketch  any thoughts?

**Comment by alex-ketch** [comment]
@nokome: If we can make some presumptions regarding the order and number of items inside each `cite` group, then I don't think we need a class.

i.e.

```css
/* pseudo CSS */

/* Numeric cite */
CiteGroup > cite > a :last-child {
  display: none;
}

/* Text cite */
CiteGroup > cite > a :first-child {
  display: none;
}
```
